services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5433
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: deel123
      POSTGRES_DB: deel
  
  api:
    image: node:18-alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app:z
    command: npm run test